### ISSUE TITLE
Mod search text box shows white text on white background with dark theme enabled

### ISSUE THREAD

**Issue by zack-emmert** [LovelessCodes/StoryForge#117]
## 🐛 Bug Report

**Describe the bug**
The search box in the mod download screen shows white text on a white background 

**To Reproduce**

1. Enable Dark Mode in settings
2. Go to Installations tab
3. Click "Manage Mods" for any installation
4. See behavior

**Expected behavior**
The search box should have a dark background so text is readable.

**Screenshots**

<img width="1411" height="1421" alt="Image" src="https://github.com/user-attachments/assets/e02f3411-7a38-474f-b265-fc883170ad5d" />

The text "Thirst" is currently in the search box in the top left.

**Environment (please complete the following information):**

StoryForge 0.5.4 installed via AppImage on Bazzite Linux with KDE.

**Comment by LovelessCodes** [comment]
Yeah - I'm in the process of migrating away from our old UI library - this should hopefully be fixed in the next big release.

**Comment by LovelessCodes** [comment]
Should be fixed in #112

**Comment by zack-emmert** [comment]
I just updated to 0.6.0 and I'm still seeing the same visual bug
